config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users
  resource :session

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :index]
    resources :workspaces
    resources :projects
    resources :workspace_memberships, only: [:create, :destroy]
    resources :tasks
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  fname           :string           not null
#  lname           :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessor :link, :ws

  validates :fname, :lname, :email, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :session_token, uniqueness: true

  attr_reader :password
  after_initialize :ensure_session_token

  has_many :user_workspaces, dependent: :destroy

  has_many :projects, through: :workspaces, source: :projects
  has_many :workspaces, through: :user_workspaces, dependent: :destroy
  has_many :associates, through: :workspaces, source: :users

  has_many(
    :team_assignments,
    class_name: "TeamAssignment",
    foreign_key: :member_id,
    primary_key: :id
  )

  has_many(
    :tasks,
    class_name: "Task",
    foreign_key: :assignee_id,
    primary_key: :id
  )

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.where(email: params[:emails])
    if @users.length < 1
      render json: params[:emails], status: 422
    # elsif @users.length != params[:emails].length

      # TODO: if you want to show errors for both not finding users and also
      # users being in the workspace, then use following code. This will
      # require refactoring some code in team_members_form.js

    #   non_existant_emails = params[:emails]
    #   @users.each do |user|
    #     non_existant_emails = non_existant_emails - [user.email]
    #   end
    #   @users << {emails: non_existant_emails}
    #   render json: @users
    else
      render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @projects = @user.projects.includes(:tasks).where({
      workspace_id: params[:workspace_id]
    })
    render :show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email.downcase, :fname.downcase, :lname.downcase, :password)
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="log-in-out-background">
  <%= image_tag 'optimized-workspace1-edited.jpg' %>
</div>

<div class="log-in-out m-content">
  <header class="heading">
    <strong>Sign Up</strong>
  </header>

  <ul>
    <% flash[:errors].try(:each) do |error| %>
      <div class="alert alert-danger" role="alert">
        <% if error == "Fname can't be blank" %>
          <li><%= "First Name can't be blank" %></li>
        <% elsif error == "Lname can't be blank" %>
          <li><%= "Last Name can't be blank" %></li>
        <% else %>
          <li><%= error %></li>
        <% end %>
      </div>
    <% end %>
  </ul>

  <form class="form-horizontal" action="/users" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label for="first-name" class="col-sm-3 control-label">First Name</label>
      <div class="col-sm-9">
        <input type="text" name="user[fname]" class="form-control" id="first-name">
      </div>
    </div>

    <div class="form-group">
      <label for="last-name" class="col-sm-3 control-label">Last Name</label>
      <div class="col-sm-9">
        <input type="text" name="user[lname]" class="form-control" id="last-name">
      </div>
    </div>

    <div class="form-group">
      <label for="email-input" class="col-sm-3 control-label">Email</label>
      <div class="col-sm-9">
        <input type="text" name="user[email]" class="form-control" id="email-input">
      </div>
    </div>

    <div class="form-group">
      <label for="password" class="col-sm-3 control-label">Password</label>
      <div class="col-sm-9">
        <input type="password" name="user[password]" class="form-control" id="password">
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-9">
        <input type="submit" value="Sign Up" class="btn btn-default">
      </div>
    </div>

    <div>Already have an account? <a href="<%= new_session_url %>">Log In</a></div>
  </form>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67284947-1', 'auto');
  ga('send', 'pageview');

</script>